### ISSUE TITLE
Private security vulnerability reporting  

### ISSUE THREAD

**Issue by Sim4n6** [voxie-viewer/voxie#2]
Dear Voxie team,

I may have identified a security vulnerability in the codebase of the latest version of voxie (not 100% sure).
I would like to report it privately. Could you please consider to opt-in this Github [feature](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability).

Kind consideration
@Sim4n6

**Comment by Sim4n6** [comment]
![image](https://user-images.githubusercontent.com/13036531/206497944-a7b876a7-cac6-4fa4-a261-cb7154f5993f.png)

**Comment by steffen-kiess** [comment]
This should be enabled by now.

**Comment by Sim4n6** [comment]
perfect, thank you.

**Comment by Sim4n6** [comment]
Regarding the potential security vulnerability, never mind it ... it was a false positive. Sorry about that.

**Comment by steffen-kiess** [comment]
> Regarding the potential security vulnerability, never mind it ... it was a false positive. Sorry about that.

No problem :-)

**Comment by Sim4n6** [comment]
I am reporting that anyway ... It is up to you to consider it.
